[package]
name = "scan"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
regex = "1.10"
rayon = "1.10"
walkdir = "2.5"
tempfile = "3.10"
fern = "0.6"
chrono = "0.4"
ibm1047 = "1"